[project]
name = "generative-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Areen Phadtare", email = "phadtareareen@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain>=1.3.14",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.4.1",
    "langgraph>=1.2.10",
    "python-dotenv>=1.2.2",
    "streamlit>=1.60.0",
]

[project.scripts]
generative-ai = "generative_ai:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
